[package]
name = "aoc02"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bimap="0.6.3"
color-eyre = "0.6.2"
itertools = "0.11.0"
